/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ModelService } from "../model.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ModelCreateInput } from "./ModelCreateInput";
import { ModelWhereInput } from "./ModelWhereInput";
import { ModelWhereUniqueInput } from "./ModelWhereUniqueInput";
import { ModelFindManyArgs } from "./ModelFindManyArgs";
import { ModelUpdateInput } from "./ModelUpdateInput";
import { Model } from "./Model";
import { ColumnFindManyArgs } from "../../column/base/ColumnFindManyArgs";
import { Column } from "../../column/base/Column";
import { ColumnWhereUniqueInput } from "../../column/base/ColumnWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ModelControllerBase {
  constructor(
    protected readonly service: ModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Model })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: ModelCreateInput): Promise<Model> {
    return await this.service.create({
      data: {
        ...data,

        project: data.project
          ? {
              connect: data.project,
            }
          : undefined,
      },
      select: {
        comments: true,
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Model] })
  @ApiNestedQuery(ModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Model[]> {
    const args = plainToClass(ModelFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        comments: true,
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        comments: true,
        createdAt: true,
        id: true,
        name: true,

        project: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() data: ModelUpdateInput
  ): Promise<Model | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          project: data.project
            ? {
                connect: data.project,
              }
            : undefined,
        },
        select: {
          comments: true,
          createdAt: true,
          id: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Model })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Model | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          comments: true,
          createdAt: true,
          id: true,
          name: true,

          project: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/columns")
  @ApiNestedQuery(ColumnFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Column",
    action: "read",
    possession: "any",
  })
  async findManyColumns(
    @common.Req() request: Request,
    @common.Param() params: ModelWhereUniqueInput
  ): Promise<Column[]> {
    const query = plainToClass(ColumnFindManyArgs, request.query);
    const results = await this.service.findColumns(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        isPrimaryKey: true,
        isUnique: true,

        model: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/columns")
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  async connectColumns(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/columns")
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  async updateColumns(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/columns")
  @nestAccessControl.UseRoles({
    resource: "Model",
    action: "update",
    possession: "any",
  })
  async disconnectColumns(
    @common.Param() params: ModelWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
